cluster-name: 'Fliwa #0'

author-name: 'subkek#0'
author-id: '667782570955767829'

license-footer: 'sub-kek © All rights reserved'
command-status-send-dm: false
command-status-ephemeral: false

command-reload-ephemeral: false

ping-command-name: 'ping'
ping-command-description: 'Calculate bot ping/latency and others.'

status-command-name: 'status'
status-command-description: 'Get base cluster status.'

reload-command-name: 'reload'
reload-command-description: 'Reload cluster config only bot author can...'

info-command-name: 'info'
info-command-description: 'Show information of the bot'